kernel/classes/ezcontentobjecttreenode.php, kernel/classes/ezurlaliasml.php, tests/tests/kernel/classes/ezcontentobjecttreenode_regression.php
JIRA: https://jira.ez.no/browse/EZP-23753
Problem:
When a node that exists on a language different from the siteaccess default language, but has a translated parent/path, the UrlAlias will be incorrect.
For example, for a "FreFolder/EnArticle" the returned alias in fre siteaccess is "EnFolder/EnArticle".
Besides incorrect, this causes additional problems when there is a `PathPrefix` setting for that SA.
This happens because `eZContentObjectTreeNode` requests the alias in the current node's language:
``` eZURLAliasML::fetchPathByActionList( "eznode", $pathArray, $this->CurrentLanguage );```
The fix from EZP-20494 (PR #572) resolved this by prefering the wanted language ONLY for the last node, and returning the rest of the path according to the prioritized languages, however it introduced a …
=> Ezp 23753 node alias translation

design/admin/templates/content/history.tpl, design/standard/templates/content/history.tpl
Since we have 2 newer object version statuses, the Manage Versions interface should show information about these new statuses.
Link: https://jira.ez.no/browse/EZP-21605
Cleaned up version of https://github.com/ezsystems/ezpublish-legacy/pull/769
=> Fix for EZP-21605: Version history Status column is missing data

design/admin/templates/ezinfo/about.tpl, design/standard/templates/ezinfo/about.tpl, kernel/ezinfo/about.php
Several changes:
- Removed hardcoded license text, instead show the whole contents of LICENSE (in legacy root) in an iframe
- Copyright year is updated to 2015
- The "What is eZ Publish?" text was split in two paragraphs in the source, this was invisible in html since there was no tagging. These are added now.
- Several text fixes (speling, punctuation etc)
- "eZ Systems", "eZ Publish" in the license text were converted to links, this is not done anymore since A) it is redundant, and B) we are now loading the whole LICENSE file and we should not mess with that - lawyers are involved.
https://jira.ez.no/browse/EZP-23879
=> Fix EZP-23879: ezinfo shows wrong copyright info after move to composer

lib/ezutils/classes/ezexpiryhandler.php
Restore timestamps before saving, to reduce chance of race condition issues
This is the easy solution. The complete solution would be an asyncronous process with expiry request stored in db and a cron daemon which processes them at short intervals. I consider that overkill for legacy, which should not have new development.
Unknown: How much does this fix affect performance in cluster environments?
https://jira.ez.no/browse/EZP-23908
=> Fix EZP-23908: expiry.php race condition

kernel/content/attribute_edit.php
> https://jira.ez.no/browse/EZP-23928
When saving a draft (not publishing), preview won't reflect the changes. A previously cached content is displayed instead.
Only applies if the frontend siteaccess is *not* using `legacy_mode`.
This patch introduces a new `content/cache/version` event.
=> Fix EZP-23928: Preview cache not being updated

kernel/private/classes/clusterfilehandlers/dfsbackends/dfs.php, lib/ezfile/classes/ezfile.php
This updates `eZFile::createFile()` so it can accept either a string or file resource as `$data` parameter.
dfs.php is updated accordingly, creating a handle using fopen() instead of passing the whole content with `file_get_contents()`.
The validity check for `$contents` in `createFile()` also applies to the handle in the same way.
=> EZP-23031: allow large file sizes on DFS without memory limitation.

kernel/classes/datatypes/ezobjectrelationlist/ezobjectrelationlisttype.php
Using current (published) content instead of original data (from when relation was added).
See change for further info on why, but in short this is already the case for generation of title and to/from string and online documentation (that code should never expect meta data like version, node id and so on to be up-to-date).
Credits: Original patch from @phalasz can be found in https://jira.ez.no/browse/EZP-24099
Expanded in this version with more doc, cs, and cleanup of variable names for readability.
=> EZP-24099: Generate relationlist metadata for Search (Solr) using published content

kernel/classes/ezcontentobjecttreenode.php
JIRA: https://jira.ez.no/browse/EZP-23725
When a different RootNode is specified for a SA, along with a PathPrefix, it's generated path will be empty;
However path_string should remain the full value.
Because path_string is based on each node's parent, simply not updating the new RootNode to empty should resolve the issue.
=> Fix EZP-23725: Wrong path_identification_string with custom RootNode

kernel/private/classes/ezpkernelweb.php, settings/error.ini
The message "Fatal error: The web server did not finish its request" cannot be overridden in eZ Publish:
https://github.com/ezsystems/ezpublish-legacy/blob/master/kernel/private/classes/ezpkernelweb.php#L213
See more at: https://jira.ez.no/browse/EZP-23913
This pull request allows this to be overridden, the developer can now define a error.ini (only in global escope, ie, settings/override/error.ini.append.php) variable like: 
[ErrorSettings-kernel]
FatalErrorHandler=CustomFatalErrorHandlerClass::FatalErrorHandlerFunction
=> Fix EZP-23913: Override legacy fatal error message

kernel/classes/ezscript.php, kernel/private/classes/ezpkernel.php
Dirty trick to see if we are in legacy context, do ob_end_clean only when we are. Seems to work.
https://jira.ez.no/browse/EZP-24135
=> Fix EZP-24135: Output buffer gets cleared after legacy call

kernel/classes/eznodeviewfunctions.php
Issue: https://jira.ez.no/browse/EZP-24154
`section_identifier` is not cached and not re applied after loading from cache, fixed in this PR by adding to `content_info`.
=> Fix EZP-24154: Overriding template with section_identifier fails when cached

bin/php/ezcache.php
Add doc about this to --help
Refuse to accept --expiry with --purge
https://jira.ez.no/browse/EZP-24197
=> Fix EZP-24197: DOC: ezcache.php --expiry parameter can only be used together with --purge

kernel/classes/datatypes/ezimage/ezimagealiashandler.php, tests/tests/kernel/datatypes/ezimage/ezimagealiashandler_regression.php
Link: https://jira.ez.no/browse/EZP-24100
When using `urlalias_iri` images are renamed with the object name. The limit for object names is by default 255 UTF-8 char (and can be customized). The problem is that most file systems have a 255 bytes limit so they won't be able to create the image file.
This patch introduces a 200 bytes limit for images (leaving a bit of room for alias name and extension).
Manual and unit tests
=> Fix EZP-24100: Image content with big multibyte charset names won't be correctly created

kernel/content/copysubtree.php
JIRA: https://jira.ez.no/browse/EZP-24223
When using MySQL master/slave setup, copysubtree will fail with a fatal error (`Call to a member function attribute() on a non-object  ...`)
This happens because a new object version is created and immediately read from (on the slave server).
Fixed by wrapping relevant section in a DB transaction.
=> Fix EZP-24233: copysubtree: wrap object copy in transaction.

lib/ezutils/classes/ezsendmailtransport.php, settings/site.ini
Link: https://jira.ez.no/browse/EZP-24233
You can also have a look at the (old): https://jira.ez.no/browse/EZP-13617
Sendmail (the MTA) doesn't support `undisclosed-recipients:;` in the `TO:` of the header. It doesn't seem to be a standard to have it there according to https://tools.ietf.org/html/rfc5322#section-3.6.3
This patch introduces a new setting. I know we are trying to avoid it, but the goal is to avoid BC breaks as much as possible. This setting allows to replace the `undisclosed-recipients:;` by an empty string.
I am not using sendmail as MTA. So I made sure  `undisclosed-recipients:;`  is removed (or not) from the headers and I did sanity tests using my MTA (exim4). It has been tested by somebody else using sendmail.
=> Fix EZP-24233: undisclosed-recipients:; breaks sendmail

kernel/classes/datatypes/ezobjectrelationlist/ezobjectrelationlisttype.php
TL;DR: Don't set draft status on the related object. Why would you want to do that?
(Warning: This involves 12+ years old code!)
Object X has an attribute level relation (object relation list) to Y. AdvancedObjectRelationList = enabled, so while editing X, we can edit Y at the same time, embedded. When autosave triggers, it sets ezcontentobject.status = draft on Y, and the bug occurs when you discard the draft of X: ezcontentobject.status of Y is not set back to published. But my fix is to never set Y's object status to draft, because I see no reason to do so:
1. While the editor is working, the relation is broken. We should not modify the state of published, live objects during editing, that's what drafts are for.
2. The ezcontentobject_VERSION of Y is correctly created as a draft while …
=> Fix EZP-24198: legacy admin: autosave will delete information about relations if AdvancedObjectRelationList = enabled

bin/php/ezsubtreecopy.php
https://jira.ez.no/browse/EZP-24289
Entirely based on schroeder's 67d95d71c0af9da20113598e3c0b0f5b5333da23 fix.
=> EZP-24289: Priority of children lost when using CLI script ezsubtreecopy.php

kernel/classes/ezpackage.php
https://jira.ez.no/browse/EZP-24333
Packages generated by ezpm.php may not include some xml elements (such as type or description),
though ezpackage import seems to require/expect these in the xml structure.
Do not assume the elements exist when parsing the xml structure, as they are not *absolutely* required.
Manual.
=> Fix EZP-24333: Fatal error importing ezpackage generated with ezpm.php

.travis.yml, extension/ezoe/ezxmltext/handlers/input/ezoeinputparser.php, kernel/classes/datatypes/ezxmltext/handlers/input/ezsimplifiedxmlinputparser.php
The PHPUnit tests currently fail when running on PHP 5.6, which seems to… different on `DOMNode`'s read-only properties than previous reasons.
Currently, e.g. the `eZXMLTextRegression::testNonBreakingSpace()` would fail, because `esp&nbsp;ace` gets "trimmed" to `esp&amp;nbsp;ace`, which is happening in [eZSimplifiedXMLInputParser::structHandlerText()](https://github.com/ezsystems/ezpublish-legacy/blob/master/kernel/classes/datatypes/ezxmltext/handlers/input/ezsimplifiedxmlinputparser.php#L687)
```php
$element->textContent = ltrim( $element->textContent );
```
`$element->textContent` is a read-only property, as [documented here](http://php.net/manual/en/class.domnode.php).
I don't know why PHP does some HTML entity encoding (that's weird) instead of emitting an error or a warning, but …
=> Fix trimming DOMElement textContent properties (re-enables PHP 5.6 on Travis)

kernel/classes/datatypes/ezbinaryfile/plugins/ezpdfparser.php
https://jira.ez.no/browse/EZP-18486
Occurs when indexing a file.
```
Notice: ob_end_clean(): failed to delete buffer. No buffer to delete. in /home/dp/dev/ezpublish/kernel/classes/datatypes/ezbinaryfile/plugins/ezpdfparser.php on line 28
Call Stack:
0.0007     405456   1. {main}() /home/dp/dev/ezpublish/runcronjobs.php:0
0.0920    6220844   2. eZRunCronjobs::runScript() /home/dp/dev/ezpublish/runcronjobs.php:329
0.1043    6288448   3. include('/home/dp/dev/ezpublish/cronjobs/indexcontent.php') /home/dp/dev/ezpublish/kernel/classes/ezruncronjobs.php:59
0.1412    9039224   4. eZSolr->addObject() /home/dp/dev/ezpublish/cronjobs/indexcontent.php:52
0.2469   14888064   5. eZSolr->addFieldBaseToDoc() /home/dp/dev/ezfind/search/plugins/ezsolr/ezsolr.php:561
0.2469   14888064   6. …
```
=> Fix EZP-18486 - PHP notice while running cronjobs/indexcontent.php cronjob

autoload/ezp_kernel.php, index_rest.php, kernel/private/rest/classes/dispatcher.php, kernel/private/rest/classes/ezpkernelrest.php, kernel/private/rest/classes/mvc_configuration.php, kernel/private/rest/classes/restkernel_functions.php
> Fixes http://jira.ez.no/browse/EZP-24278
> Requires ezsystems/LegacyBridge#25
This PR adds the required elements (custom kernel, mostly) to run the V1 REST API through the new stack.
index_rest.php is still used, but it uses the custom rest kernel instead.
=> EZP-24278: Add new stack kernel around REST API v1

kernel/classes/ezcache.php, lib/ezutils/classes/ezextension.php
JIRA: https://jira.ez.no/browse/EZP-24419
Cache files for active_extensions aren't removed when clearing/purging caches.
Make sure to remove them :)
Note that `ClusterFileHandler` isn't used here, also active extension cache is hardcoded to var/cache.
As no record of files is kept, the proposed solution is to have eZExtension clean up the stale files much in the same way as it creates them: manually (see [ezextension.php#L115](https://github.com/ezsystems/ezpublish-legacy/blob/master/lib/ezutils/classes/ezextension.php#L115) ).
Manual.
=> Fix EZP-24419: clear stale active_extension cache files.

lib/ezutils/classes/ezhttptool.php
JIRA: https://jira.ez.no/browse/EZP-20723
This uses CURLOPT_CUSTOMREQUEST ( GET ) together with CURLOPT_NOBODY options to mimic 'HEAD' requests when using curl.
In addition, also get result data from curl as string, instead of capturing the output buffer.
=> EZP-20723: linkcheck cronjob: some urls marked invalid due to HEAD request

extension/ezoe/design/standard/javascript/ezoe/popup_utils.js
JIRA: https://jira.ez.no/browse/EZP-24240
It's an alternative to https://github.com/ezsystems/ezpublish-legacy/pull/1166. Instead of fixing the potential multiple remaining ids afterwards, this patch uses a special class and make sure to clean up right after we don't need it anymore.
manual tests
=> Fix EZP-24240: Incorrect links when applied on multiple lines

kernel/content/urlalias_wildcard.php
At /content/urlwildcards, when the user creates an URL wildcard alias starting with a slash, it will not get matched.
I think the easiest solution would be to trim leading slashes from the wildcard when the user enters it, so here it is.
While at it, I also added a `/** @var eZModule $Module */` at the top of the file to satisfy IDEs and fixed a possible E_NOTICE for a possibly undefined `$limitValues` variable and a missing index. PHPStorm code inspection rules :).
https://jira.ez.no/browse/EZP-21477
Cheers
:octocat: Jérôme
=> Fix EZP-21477: URL wildcards with leading slash are not matched

lib/ezsession/classes/ezpsessionhandlersymfony.php
> https://jira.ez.no/browse/EZP-24334
Some scripts, like `ezpm.php`, initialize `eZScript` with session support.
In that case, when shutting down, `eZScript` tries to log out current user and to clean up the session. This calls `ezpSessionHandlerSymfony`, which calls Symfony session storage, which does... a legacy callback.
This patch ensures that calls to session regenerate/destroy/gc in `ezpSessionHandlerSymfony`, and  made from CLI doesn't do anything.
AFAICS, there should not be any BC break.
=> Fix EZP-24334: Error exporting ezpackage with ezpm.php through ezpublish:legacy:script

extension/ezoe/design/standard/javascript/ezoe/popup_utils.js
JIRA: https://jira.ez.no/browse/EZP-24240
The fix for [EZP-24240](https://jira.ez.no/browse/EZP-24240) provided in https://github.com/ezsystems/ezpublish-legacy/pull/1176 was incomplete. This patch makes sure we don't re-add the custom temporary class `ezoeInsertedLink` otherwise if you create several links in a row, they'll all have the target of the last one.
manual tests
=> EZP-24240: Make sure the custom temporary class is not added back on links

extension/ezoe/design/standard/templates/ezoe/customattributes/link.tpl
JIRA: https://jira.ez.no/browse/EZP-24492
The "link" attribute of a custom tag can be unusable if the custom tag name contains an underscore. This is happening because several elements ids are computed by splitting a string containing the tag name with the underscore as a separator.
This patch makes sure we don't take the tag name into account when computing the elements ids.
manual tests (on the link tag and custom tags with and without underscores)
=> Fix EZP-24492: link attributes unusable with custom tag containing underscores

kernel/classes/datatypes/ezobjectrelationlist/ezobjectrelationlisttype.php
Given a content that has a relation list field, and has one translation in a secondary language with relations in the relation list field, publishing a new translation in the main language will remove the relations in other languages.
The lines that are removed go back to 2005 (@45eb5e7), and don't reference a bug, meaning that we don't really know what it fixed (something with reverse relations).
1. Site has eng-GB and fre-FR, and a Content Type "Relation list" with a relation list attribute
2. Create a content of type "Relation list" in eng-GB, with a relation to object A
3. Edit the content in fre-FR, and add a relation to object B
4. Check in the object's relations tab that both relations to A and B are listed
5. Edit the content in eng-GB, publish without changing it
6. Check in the …
=> Fix EZP-24530: Editing other language removes translations

design/admin/templates/content/history.tpl
Link: https://jira.ez.no/browse/EZP-24641
Forms with the same action were nested (see opening tag line 49), which is not allowed by (modern) browsers.
The fix removes the nested form tags.
Manual test and sanity checks on the page
=> Fix EZP-24641: Copy button next to Published article not triggering an action

design/admin/templates/content/edit_conflict.tpl, kernel/classes/datatypes/ezboolean/ezbooleantype.php
Link: https://jira.ez.no/browse/EZP-24630
A 10 year old bug (at least).
I added comments in the code with explanations. 
The main idea is that DataTypes check if a value is present in POST and return false when a content should not be modified (nothing to do). 
The problem is that HTTP checkboxes "unchecked" value is "not being present in POST" making it impossible to know if the DataType needs to return false (nothing to do) or to update the data with "unchecked". The bug is that it was updating the data with "unchecked".
In order to fix that, I added checkboxes values in an hidden field in the conflict page which is a "nothing to do" case DataTypewise.
Manual tests and sanity tests on checkbox editing
=> Fix EZP-24630: Checkbox value lost when conflicts

settings/textfile.ini
Currently file register users on Admin Group
Fixes: https://jira.ez.no/browse/EZP-24734
Where the objectId is used: https://github.com/ezsystems/ezpublish-legacy/blob/master/kernel/classes/datatypes/ezuser/eztextfileuser.php#L186
=> Fix EZP-24734: Users (eztextfileuser) created in wrong group

kernel/classes/ezcontentobjecttreenode.php, tests/tests/kernel/classes/ezcontentobjecttreenode_test2.php
https://jira.ez.no/browse/EZP-24565
Replaces https://github.com/ezsystems/ezpublish-legacy/pull/1182 : the approach is not right as every items of the in/not_in statement must have the same type (either string or integer) to be properly quoted in the final SQL query.
TODO:
=>  Fix EZP-24565: correctly quote attributes of custom AttributeFilters

kernel/private/classes/ezautoloadgenerator.php
See https://jira.ez.no/browse/EZP-24868
Since PHP 5.5, it is possible to use `<ClassName>::class` for class name resolution, in addition to `get_class()`, see [PHP Manual: OOP Basics -> ::class](http://php.net/manual/en/language.oop5.basic.php#language.oop5.basic.class.class).
When this is used anywhere in a file parsed by the autoload generator, PHP Notices are thrown during generation:
```bash
$ php bin/php/ezpgenerateautoloads.php -e
Scanning for PHP-files.
Scan complete. Found 1525 PHP files.
Searching for classes (tokenizing).
PHP Notice:  Uninitialized string offset: 1 in kernel/private/classes/ezautoloadgenerator.php on line 632
PHP Stack trace:
PHP   1. {main}() bin/php/ezpgenerateautoloads.php:0
PHP   2. eZAutoloadGenerator->buildAutoloadArrays() …
```
=> EZP-24868: Ignore class token if prefixed by "::"

cronjobs/indexcontent.php
We clear in-memory cache for each normal indexed object, but not for moved node subtrees.
https://jira.ez.no/browse/EZP-24889
=> Fix EZP-24889: Clear in-memory cache for moved nodes in delayed indexing script

kernel/classes/datatypes/ezbinaryfile/ezbinaryfiletype.php
JIRA: https://jira.ez.no/browse/EZP-24692
When creating a video content the first upload creates a binaryfile entry, but saving or publishing the 1st version will create yet another file.
The DB entry in ezbinaryfile is updated for that version, so the file kept in var/storage becomes 'stale'.
This fix makes sure that the old file is removed when storing a new file for a given version.
Notes: 
*  fileName is not the actual (original) filename, but the pseudo-random hash.ext that can be seen under var/storage/
* `deleteStoredObjectAttribute()` method should only remove the file if no longer in use.
=> Fix EZP-24692: creating content leaves stale video/binary files

kernel/pdf/list.php
A small issue, but causes exception in Symfony context where ez_legacy route fails with an error about non existing module "kernel".
Link: https://jira.ez.no/browse/EZP-24906
=> EZP-24906: Fix breadcrumb link to pdf/list module

cronjobs/indexcontent.php
An alternative to https://github.com/ezsystems/ezpublish-legacy/pull/1204 with a simpler diff: duplicating the DB commands.
=> Fix EZP-24890: Delayed indexing should fail gracefully on trashed / broken node (alt)

cronjobs/indexcontent.php
This was discovered when fixing #1206 and split into its own issue.
Link: https://jira.ez.no/browse/EZP-24918
=> Fix EZP-24918: Delayed indexing: moved nodes logic skips normal pending objects

design/admin/stylesheets/pagelayout.css
https://jira.ez.no/browse/EZP-25017
This restores the language indicator to be below the title, on the same line as the author, object ID, and node ID information.
=> Fix EZP-25017: Administration Interface object title runs over language indicator

extension/ezjscore/classes/ezjscserverfunctionsjs.php
JIRA: https://jira.ez.no/browse/EZP-25036
With this change it is possible to get the data map from the search results.
I need it to display additionally fields for the ezrelationlist ajax search.
=> EZP-25036: Add EncodingDataMap Parameter to ezjsc::search Ajax function

update/common/scripts/5.4/fixtrashedimagereferences.php
JIRA: https://jira.ez.no/browse/EZP-25077
due to a bug on ezimage datatype on <= 5.3.2 , trashing a content with an empty image would result in an attribute with the following:
```
<ezimage serial_number="1" is_valid="" filename="c992d69f74dcf51ff04a051ef0d93d6b." suffix="" basename="c992d69f74dcf51ff04a051ef0d93d6b" dirpath="/trashed" url="/trashed/c992d69f74dcf51ff04a051ef0d93d6b." original_filename="" ... 
```
This has been resolved, but not at the DB level.
With the new alias handling mechanism in 5.4.4, operations on these files (such as clearing the trash) will result in a fatal exception.
Add a script to cleanup these invalid references in empty, trashed, ezimage attributes.
The script should be able to handle thousands of attributes due to it's simple operation, in any case a …
=> Fix EZP-25077: invalid image refs on trashed content with empty images

update/common/scripts/5.4/fixtrashedimagereferences.php
Somehow the string comparison for matching invalid/empty, trashed images was incorrect, this fixes it.
=> EZP-25077: fix incorrect order of trashed image validity check.

extension/ezjscore/classes/ezjscserverfunctionsnode.php, kernel/content/action.php, kernel/content/ezcontentoperationcollection.php
JIRA: https://jira.ez.no/browse/EZP-24783
Some node sort operations (either through content/action, content operation or ezjscore) clear cache without checking if it is enabled or not.
=> Fix EZP-24783: only clear cache if needed in sort operations

kernel/classes/datatypes/ezisbn/ezisbntype.php
JIRA: https://jira.ez.no/browse/EZP-18202
When clearing an isbn13 field that was already filled in (and the field is not required), saving will not actually clear the field / save the empty value.
This makes it so the empty value is actually saved.
=> Fix EZP-18202: Impossible to clear previously populated ISBN field

kernel/classes/datatypes/ezobjectrelation/ezobjectrelationtype.php
JIRA: https://jira.ez.no/browse/EZP-25065
When editing content with multiple languages and a non-translatable object relation, updating the relation object will cause the object to incorrectly display both the previous and the new relation.
When the relation attribute is non-translatable, remove any existing relation when storing a new one, regardless of the number of current translations.
=> Fix EZP-25065: non-translatable object relation not updated.

update/common/scripts/5.4/cleanuntranslatablerelations.php
JIRA: https://jira.ez.no/browse/EZP-25292
This adds an additional check for non-translatable relation(s) cleanup script in #1227
For cases where the `data_text` column of relationlist attribute is `null`, for whatever reason, the script would try to access a non-object when processing the relations xml.
Ref: `eZObjectRelationListType` @ https://github.com/ezsystems/ezpublish-legacy/blob/master/kernel/classes/datatypes/ezobjectrelationlist/ezobjectrelationlisttype.php#L1415
=> Fix EZP-25292: additional check for relationlist xml

kernel/classes/ezpersistentobject.php
Link: https://jira.ez.no/browse/EZP-25455
Oracle uses short_names in ezPersistentObject to access DB field values.
The Bugfix ensures that the correct replacement of the attribute short_names with the longnames will be used
for objectcreation!
The first &$row is used for correct replacement and the second $row fixes an issue where rsults are correctly used for objeccreation
(otherwise e.g. worflow/grouplist was not shown correctly  3 groups but only 2 where displaxed one was overriden)
=>  Fix EZP-25455: eZOracle: Link management doesn't show objects

extension/ezoe/tests/ezoexmltext_regression.php, kernel/classes/datatypes/ezxmltext/ezxmlinputparser.php
JIRA: https://jira.ez.no/browse/EZP-26096
This patch fixes an issue in ezxmltext input parser which breaks when an attribute contains a `>`. Basically, to correctly detect an opening tag it's not enough to search for the next `>` after a `<` because the next `>` can be inside an attribute.
manual + unit tests
=> Fix EZP-26096: Custom tags' text line parameters not saved correctly

extension/ezoe/design/standard/javascript/ezoe/popup_utils.js
JIRA: https://jira.ez.no/browse/EZP-26108
Before this patch, if you type something right after adding a block custom tag, the content of the ezxmltext attribute is messed up. For instance, in Chrome, the following paragraph is added to the custom tag content, in Firefox, the custom tag is completely removed. This is happening because the newly added custom tag was completely selected, with the patch only its content is selected.
manual tests
=> Fix EZP-26108: Typing right after adding a block custom tag breaks the contents

extension/ezjscore/classes/ezjscpacker.php
https://jira.ez.no/browse/EZP-19376
This makes sure that urls in CSS are not replaced with paths "recursively", see original description:
> When a file contained this kind of url :
> ```
>   src: url("fonts/HelveticaNeue55-Roman.eot");
>   src: url("fonts/HelveticaNeue55-Roman.eot?#iefix") format("embedded-opentype");
> ```
> we had these lines in return :
> ```
>   src: url("/extension/my_extension/design/my_design/fonts/HelveticaNeue55-Roman.eot");
>   src: url("/extension/my_extension/design/my_design//extension/my_extension/design/my_design/fonts/HelveticaNeue55-Roman.eot?#iefix");
> ```
Alternative for https://github.com/ezsystems/ezpublish-legacy/pull/1163 , which addresses the complexity of the initially proposed fix.
=> Fix EZP-19376: ezjscore CSS packer duplicate url path replacement

extension/ezoe/tests/ezoexmltext_regression.php, kernel/classes/datatypes/ezxmltext/ezxmlinputparser.php
JIRA: https://jira.ez.no/browse/EZP-26096
This is an additional fix with the corresponding unit test for https://github.com/ezsystems/ezpublish-legacy/pull/1249 provided by @pkamps in https://github.com/ezsystems/ezpublish-legacy/pull/1249#discussion_r73696903 (thanks :)) because the original fix was only working if there was only one attribute with a `>`.
manual tests + unit tests
=> Fix EZP-26096: additional fix to handle several attributes with special characters

doc/bc/5.4/changes-5.4.txt, doc/features/5.4/event.txt, extension/ezoe/ezxmltext/handlers/input/ezoexmlinput.php, kernel/classes/datatypes/ezxmltext/handlers/input/ezsimplifiedxmlinput.php, kernel/classes/datatypes/ezxmltext/handlers/output/ezpdfxmloutput.php, kernel/classes/datatypes/ezxmltext/handlers/output/ezplainxmloutput.php, kernel/classes/datatypes/ezxmltext/handlers/output/ezxhtmlxmloutput.php, kernel/content/ezcontentoperationcollection.php
Ports:
- EZP-26028: Unable to use Online Editor when using PHP7
- EZP-25089: Object state changes/assignments does not clear persistence cache in platform stack
Closes #1257, #1255, #1254
=> Port of EZP-25089 (object state) & EZP-26028 (ezoe php7 support)

lib/ezutils/classes/ezexecution.php
> https://jira.ez.no/browse/EZP-26300
With PHP 7, exception handlers can now receive `Error` exceptions. Those exceptions are internal to PHP and are not directly linked to `Exception` class, except that they both implement `Throwable` interface, which is present in PHP 7 only.
This patch just removes `Exception` type hint in `eZExecution::defaultExceptionHandler()` in order to avoid fatal errors when receiving the new `Error` exceptions.
=> Fix EZP-26300: Fatal error when going through defaultExceptionHandler with PHP7

lib/ezi18n/classes/ezchartransform.php
Fix for https://jira.ez.no/browse/EZP-14719 (old zombie issue)
https://jira.ez.no/browse/EZP-26276 (new incarnation)
`This is "My Article!"` becomes `This-is-My-Article!`. The exclamation mark should not be there.
=> EZP-26276: Exclamation mark followed by non-chars at end of URL does not work in emails

extension/ezoe/design/standard/javascript/themes/ez/editor_template.js
JIRA: https://jira.ez.no/browse/EZP-26354
In OE, when an URL is recognized, a link is automatically created. This is done by the autolink TinyMCE plugin but the markup generated is a bit different than the one generated by the regular insert link tool. Mainly it does not add the `data-mce-href` attribute. Unfortunately, this attribute is expected by some code added to work around an IE bug. So this patch improves the workaround so that it won't break links without the `data-mce-href` attribute.
manual tests (including in IE8)
=> Fix EZP-26354: Autolink fails if you try to link content in your own site

extension/ezoe/design/standard/javascript/ezoe/popup_utils.js
JIRA: https://jira.ez.no/browse/EZP-26427
eZOE popup utils does not urlencode form parameters, which can result in query strings being broken/ incorrectly split (eg: `some&string` => `/call?SearchStr=some&string& ...` )
=> Fix EZP-26427: ezoe popup search string not urlencoded

kernel/content/ezcontentoperationcollection.php
> https://jira.ez.no/browse/EZP-26449
When publishing a content from legacy (e.g. from admin interface), `content/publish` operation copies missing translations on the published version.
However, `eZContentOperationCollection::copyTranslations()` ignores the version language mask when retrieving the translation list for the version to publish, using `$version->translationList( false, false )`. While this is usually fine as a translation is generally a full bunch of translated attributes, this can lead to unexpected behavior, especially when using a mix of legacy and platform scripts.
Typical example is when using a _wait until date_ workflow (legacy admin/kernel), combined with several scripts from Symfony stack, like migration scripts for example:
- Webmaster publishes from admin …
=> Fix EZP-26449: Wrong version translation list in eZContentOperationCollection

kernel/classes/datatypes/ezxmltext/ezxmlinputparser.php, tests/tests/kernel/datatypes/ezxmltext/handlers/input/ezsimplifiedxmlinputparser_regression.php
JIRA: https://jira.ez.no/browse/EZP-26832
This patch fixes a regression caused by https://github.com/ezsystems/ezpublish-legacy/pull/1249 where the eZSimplifiedXMLInputParser does not accept URL with non XML encoded ampersand (so containing `&` instead of `&amp;`)
manual tests + unit test
=> Fix EZP-26832: Enabling editor causes error on links with "&"

kernel/classes/eznodeviewfunctions.php, settings/site.ini
This pull request adds a setting to have different content cache based on request protocol (https vs http).
This is required if your site runs both http and https. If you build full URLs in your content area - those full URLs get cached as content cache. In that case you want to enable the setting to have 2 different content cache versions based on the request protocol.
=> Setting to have different cache based on the request protocol

kernel/common/ezautolinkoperator.php, tests/tests/kernel/common/ezautolinkoperator_test.php, tests/tests/kernel/suite.php
Issue: https://jira.ez.no/browse/EZP-27092
Remove eZAutoLink operator usage of preg_replace usage of "\e" (PREG_REPLACE_EVAL) to properly support php 5.5+ and php 7.0+
Since PHP 5.5.x the usage of preg_replace() function no longer supports "\e" (PREG_REPLACE_EVAL) and preg_replace_callback() should be used instead. IE: Deprecation of feature usage.
Since PHP 7.x the usage of preg_replace() function no longer supports "\e" (PREG_REPLACE_EVAL) and preg_replace_callback() must be used instead. IE: Removal of feature usage.
Source #1, Deprecated features in PHP 5.5.x: http://php.net/manual/en/migration55.deprecated.php
Source #2, Changed functions in PHP 7.x: http://php.net/manual/en/migration70.changed-functions.php
Description Summary: preg_replace() function no longer supports "\e" …
=> EZP-27092: Remove eZAutoLink operator usage of preg_replace and PREG_REPLACE_EVAL

kernel/content/ezcontentoperationcollection.php, settings/audit.ini
We just ran into an issue on one of our customers where it would have been really good to know who made a state change. Thus it would be good to make this an audit log event.
@peterkeung
=> Add state change/assign to the audit log

autoload.php
When generating autoloads on a fresh ezpublish-legacy install through Symfony, the missing file raises a notice which is caught by the Symfony exception handler - This means that the autoloads can't be generated through Symfony, unless they have previously been generated by legacy.
This change is trivial and mitigates the issue.
Duplicate/response to https://jira.ez.no/browse/EZP-15983 - Please don't hate me for using a file_exists @bdunogier!
=> EZP-15983 - Only include ezp_override when present

lib/eztemplate/classes/eztemplatearrayoperator.php
> Issue: https://jira.ez.no/browse/EZP-27360
See:
https://github.com/mugoweb/ezpublish-legacy/pull/57
Originally fixed by Graham: ezsystems#1162 (you probably want to close the pull request if this pull requests gets merged)
=> EZP-27360: Make Template Operators utf8 friendly

design/admin/templates/content/parts/object_information.tpl
> [EZP-27306](http://jira.ez.no/browse/EZP-27306)
#
When an object info shows incorrect "modifier" name (displaying the modifier of the latest version instead, which is a draft created by modifying an object, which means that modifier name always shows the name of the current user).
This bug was introduced by this PR: https://github.com/ezsystems/ezpublish-legacy/pull/1114.
To make it work in edit view and version view, I suggest using published version instead of the latest version to retrieve the name of modifier. It seems logical modifier to me in both situations. We can't use the latest version, because of the reason mentioned above. We also can't use "object.current", because it introduces bug [EZP-23672](http://jira.ez.no/browse/EZP-23672).
I used "foreach" to retrieve published …
=> FIX EZP-27306: Display modifier of published version in edit view and in version view

kernel/classes/datatypes/ezuser/ezuser.php
This is a proposed solution for https://jira.ez.no/browse/EZP-27427
A problem of deadlock / lock timeout came up in https://jira.ez.no/browse/EZP-25916. It occurs on high load environments with DFS cache setup with mysql as a cache metadata repository.  While handling of mysql lock errors is handled in #1301 this work tries to speed up things to reduce the dead lock situations in the first place.
Basically what I have done here is a strip down of @joaoinacio work to do as few code modifications as possible since we are in legacy.
Up to now `generateUserCacheData` method resulted in querying mysql 4 times for group ids:
[First](https://github.com/ezsystems/ezpublish-legacy/blob/master/kernel/classes/datatypes/ezuser/ezuser.php#L1419) …
=> EZP-27427 Cache generation performance improvement

kernel/content/restore.php
This is a fix for https://jira.ez.no/browse/EZP-26013
While restoring object from trash it's cache was not refreshed. The issue here was that when logic which is meant to clear the cache was run it was [called](https://github.com/ezsystems/LegacyBridge/blob/master/bundle/Cache/PersistenceCachePurger.php#L129) with array of locationIds 
One of ids passed to this method was a locationId after restoration of object. Because this method was run before performing mysql commit it threw an exception as content could not be found.
So easy fix for this is just doing commit before trying to restore caches.
=> EZP-26013 cache update on trash restoration

kernel/classes/ezurlaliasml.php
[https://jira.ez.no/browse/EZP-27474](https://jira.ez.no/browse/EZP-27474)
#
Excerpt from the JIRA issue:
> When trying to add an URL alias to a node (content/urlalias/) where the same URL alias already exists in another language, the following error message is produced: The URL alias <</xxx>> already exists, and it points to <<content/view/full/xxx>>. As it is an alias for another language, it should be created anyway.
The solution proposed in this PR was originally proposed by @glye here: https://jira.ez.no/browse/EZP-16680. It was tested by me and it solves the issue.
=> Fix EZP-27474: Unable to add the same URL alias for other languages

kernel/private/classes/clusterfilehandlers/dfsbackends/mysqli.php
This is a fix for https://jira.ez.no/browse/EZP-25916 
In high load environments it is possible that multiple processes are trying to perform the same operation (cache generation) on mysql database which may result in one of [Lock wait timeout exceeded; try restarting transaction](https://dev.mysql.com/doc/refman/5.5/en/error-messages-server.html#error_er_lock_wait_timeout) (error number 1205) or [Deadlock found when trying to get lock; try restarting transaction](https://dev.mysql.com/doc/refman/5.5/en/error-messages-server.html#error_er_lock_deadlock) (error number 1213)
Currently those errors aren't handled and are treated as a `Unexpected error` resulting with a crash.
The idea behind this solution is to treat those errors similar as …
=> EZP-25916: fixing deadlock issues on clustering cache

kernel/classes/ezinformationcollection.php, kernel/content/collectedinfo.php, settings/collect.ini
> JIRA: https://jira.ez.no/browse/EZP-27091
Currently, to be able to view collected information on frontend e.g. poll results, a user must submit a form in a current session (introduced in 3929217). This behavior is expected for forms with sensitive data (e.g. contact form, abuse report), but not necessarily in others use cases (e.g polls).
This PR adds a "CollectSensitiveData" and "CollectSensitiveDataList" settings to mark data collections as a "containing sensitive data". Depending on those settings user is allowed (or not), to view collected information without a previously form submit.
=> EZP-27091: Added a settings to mark data collections as a "containing sensitive data"

extension/ezoe/ezxmltext/handlers/input/ezoeinputparser.php, extension/ezoe/ezxmltext/handlers/input/ezoexmlinput.php, extension/ezoe/tests/ezoexmltext_regression.php, kernel/classes/datatypes/ezxmltext/ezxmlinputparser.php
The ezxmltext datatype allows editors to embed custom tags. For example the 'factbox'. A custom tag may have input fields allowing the editor to type in text. For example 'Title' for the 'factbox'.
If you type in a " (double-quote) char into the custom tag field, it is getting encoded twice before the value gets stored in the database. That's problematic because the template that renders the custom tag is not receiving the " char but '&quot;' instead.
Steps to reproduce the issue:
- you have a xmltext attribute (like article body)
- in this attribute you add a custom tag
- the custom tag has an field and you add some HTML code into this field - something like "<iframe src="http://www.mugo.ca"></iframe>"
- You save the content object (Send to publishing)
- On the public site, the HTML for …
=> EZP-27171: Fix escaping for custom tag attribute values

lib/eztemplate/classes/eztemplatemultipassparser.php
Using $tagPosition brings a notice that it does not exists => the variable to use is $tagPos
=> EZP-27714: Replaced wrong variable name in eZTemplateMultiPassParser class

tests/toolkit/ezpdatabasesuite.php
ezpDatabaseTestSuite is the parent class for a lot of test classes that need a DB connection. In the setUp(), it is setting the DB environment. This patch is simply moving that logic into a dedicated PHP function setDatabaseEnv(). In setUp() it's just calling the function - so basically no changes in the logic, just the code organisation changed.
Why is that even worth doing?
Normally, you can write a single test in a single test function. But you can also use PHPUnit Data Providers - it's splitting the test into 2 functions:
https://phpunit.de/manual/current/en/writing-tests-for-phpunit.html#writing-tests-for-phpunit.data-providers
The unit test in the ezfind extension are using that approach. There is a problem with the order of how the PHPUnit framework calls the functions:
1. Calls …
=> Unit test db setup

kernel/common/ezwordtoimageoperator.php
Currently the fallback when looking for icon sizes grabs the icon with the key `0`, but there are instances where there is nothing set at that key. I assume the author was meaning to grab the first icon size in the array, so I propose switching this to use reset.
=> EZP-27257: Handle non-numeric image size keys better

kernel/content/module.php
> https://jira.ez.no/browse/EZP-26070
> https://github.com/ezsystems/ezpublish-kernel/pull/1868
This PR adds a `content/publish` policy, unused by the Legacy itself, instead used for compatibility with eZ Publish 6.8.x kernel.
=> EZP-26070: Add support for content/publish policy

kernel/classes/ezcontentobject.php, kernel/content/restore.php
This is a fix for https://jira.ez.no/browse/EZP-26013 and follow up to #1306 
Previous PR was only partial fix. It worked only in case item restored from trash was an object of reverse relation. 
In order to fix it for all cases `commit` need to go further up, before method which is doing content publish.
//CC @lserwatka
=> EZP-26013 moving commit before method which publishes content

kernel/classes/datatypes/ezobjectrelation/ezobjectrelationtype.php, kernel/classes/datatypes/ezobjectrelationlist/ezobjectrelationlisttype.php
> Issue: https://jira.ez.no/browse/EZP-27746
When editing (translatable) relation(s), only the relations for the published versions (of any language) should remain in the object relations table.
- [EZP-25396](https://jira.ez.no/browse/EZP-25396): Clean obsolete object relations (list) on publish
- [EZP-25848](https://jira.ez.no/browse/EZP-25848): PostgreSQL regression in objectrelation/list
- [EZP-27493](https://jira.ez.no/browse/EZP-27493): Typos in eZObjectRelation[List]Type
=> EZP-27746: Obsolete object relations not cleaned up

composer.json
As part of [2017.08](https://github.com/ezsystems/ezpublish-legacy/milestone/1) milestone we are currently merging a few new features to keep legacy compatible with latests version of eZ Platform, which will cause issues if they it is used together with older kernel installs like 6.7 and 5.4.
This was suggested by @emodric in [ongoing](https://github.com/ezsystems/LegacyBridge/pull/103) work to simplify legacy bridge install, where simplifying also tries to avoid people ending up in non working package combinations.
=> [Composer] Specify conflict with kernel older then 6.11

kernel/content/ezcontentoperationcollection.php
JIRA issue: [https://jira.ez.no/browse/EZP-27735](https://jira.ez.no/browse/EZP-27735)
First change of content priority was incorrectly indexed in Solr. Instead of new value, default 0 value was indexed.
=> EZP-27735 Solr index not updated immediately after change content priority

composer.json
Because of bug in composer (composer/composer#5505), where alias of dev-master _(and possible other dev branches)_ is not resolved on `conflicts` statements, we need to keep the comparison here under dev-master version number (9999999-dev).
Upper bound could have been set to 9999, but in case of future community releases of kernel, opted for 2017.08 which means 6.11 here.
=> [Composer] Avoid conflict with dev-master of kernel

kernel/user/ezuseroperationcollection.php
> https://jira.ez.no/browse/EZP-28010
Now that #1322 is implemented, it would be wise to update the hash to the new default whenever a user changes the password.
=> EZP-28010: Update password hash type to current default when changing the user password

kernel/private/classes/exceptions/database/exception.php, lib/ezdb/classes/ezmysqlidb.php
Bug report: https://jira.ez.no/browse/EZP-27814
Since eZ Publish 4.5, we can catch DB exceptions: https://github.com/ezsystems/ezpublish-legacy/blob/master/doc/features/4.5/ezdb_exception_based_error_handling.txt
However, the error code in the DB exception is always 0. This pull request logs the MySQL error code in the exception code so that you can specifically catch error codes (such as deadlocks) and act accordingly (such as retrying the transaction).
One of the reasons this is important is that the legacy API is prone to DB deadlock errors on concurrent object creation.
You can reproduce this quite easily by running multiple versions of this script at the same time:
```
<?php
for( $i = 0; $i < 100; ++$i )
{
$params = array();
$params['class_identifier'] = 'folder'; …
```
=> Fix EZP-27814: Support MySQL error codes in DB exceptions

kernel/classes/ezpersistentobject.php
That's another issue caused by
https://github.com/ezsystems/ezpublish-legacy/pull/1233
It will avoid warnings like:
```Unexpected error, the message was : Too few arguments to function eZPersistentObject::__construct(), 0 passed in /var/www/website/kernel/content/versionview.php on line 191 and exactly 1 expected in /var/www/website/kernel/classes/ezpersistentobject.php on line 52```
It will allow to initiate eZPersistentObjects without any $row values. For example:
https://github.com/mugoweb/ezpublish-legacy/blob/master/kernel/content/versionview.php#L191
*Reproduce the issue*
In the admin interface, go to a versionview page. For example under the 'Manage versions' screen.
=> Making the constructor parameter $row optional

kernel/search/plugins/ezsearchengine/ezsearchengine.php
When updating object_count in ezsearch_word, eZSearchEngine splits the list of words in chunks of 500. But in every cycle of the loop not only the current chunk but all of the previous chunks are incremented. Which means that if there are, lets say 3 chunks, the first chunk gets an increment of +3, the second of +2, and the third of +1.
Steps to reproduce:
1. Create a new object with an attribute that has (plenty) more than 500 indexable words.
2. Pick any word that is mentioned at the beginning of that attribute.
3. Publish the object
4. Find that word in ezsearch_word and watch the object_count value.
5. Edit the object created in step 1 and publish it without modifying it.
6. Find again the word in ezsearch_word and watch the object_count value.
Result:
The object_count has a larger …
=> Fix EZP-28165: Incorrect increment of object_count in ezsearch_word

lib/ezimage/classes/ezimagemanager.php, settings/image.ini
https://jira.ez.no/browse/EZP-27993
In eZ Publish legacy, we can set a global image quality in image.ini, but cannot override this per alias.
This is the reverse problem as eZ Platform / new stack, where you can set the quality by alias but cannot set a global value (https://github.com/liip/LiipImagineBundle/pull/909).
This way, you can set something like this in image.ini to override the global setting:
```
[medium]
Quality[]
Quality[]=image/jpeg;80
```
=> EZP-27993: Support quality override by image alias

kernel/classes/ezsitedata.php, tests/tests/kernel/classes/ezsitedata_test.php
Most changes are due to code reformatting. I added a new function "create" to simplify the creation process.
The function has a new unit test.
=> [EZP-28180] Adding function "create" to simplify the creation of a ezsitedata entry

extension/ezoe/ezxmltext/handlers/input/ezoeinputparser.php
> JIRA: https://jira.ez.no/browse/EZP-28174
This PR improves an error message when target of `eznode://` and `ezobject://` links don't exist.
=> EZP-28174: Improved error message when target of eznode:// and ezobject:// links doesn't exist

settings/datetime.ini
I copied the documentation from the ez site into the ini file. Additionally I added a few more useful examples for dates and times.
=> datetime.ini: Inline doc added. Better examples

kernel/search/plugins/ezsearchengine/ezsearchengine.php, lib/ezdb/classes/ezdbinterface.php
Alternative to https://github.com/ezsystems/ezpublish-legacy/pull/1268
=> Fix EZP-26209: Textline legacy search indexing causes TransactionError

extension/ezjscore/classes/ezjscpacker.php
image path like background-image: url('../images/sample@2x.png'); wasnt replaced during CSS Compressing
=> CSS Compressing was ignoring @2x image path

kernel/classes/ezsiteinstaller.php
> Regression from #1233
Given this is used by existing packages we need to make sure it still works with old style.
=> Add compat layer for constructor for eZSiteInstaller

kernel/classes/ezscript.php
Happens when running scripts:
```
eddie@abyss [~/www/ezpublish_legacy] ( ± master ) $ php bin/php/flatten.php all
PHP Warning:  count(): Parameter must be an array or an object that implements Countable in /media/eddie/data/html/ezpublish_legacy/kernel/classes/ezscript.php on line 1075
```
I'm sure there are more places where this happens, too :)
=> Fix warning on counting NULL in PHP 7.2

autoload.php, bin/php/ezpgenerateautoloads.php, composer.json, config.php-RECOMMENDED
Mainly in order to solve the autloading issue with eZ Platform v2, but also:
- Allows standalone usage in scripts using [standard composer autoload](https://getcomposer.org/doc/01-basic-usage.md#autoloading)
- Automatically generates autoload on composer install / update _(when legacy is root package. In legacy bridge setup, legacy bridge handles this and more)_
- Removes the dead code around PEAR and bundled ez Components which is not relevant anymore, and actually risky since they don't received (security) updates anymore
Result is more clean autoloading code which just have three cases to care about in regards to making sure things like Zeta Components are loaded.
=> [Feature] Change to use Composer for autoload, drop PEAR/EZC

design/admin/templates/content/parts/object_information.tpl
> JIRA ticket: [EZP-28750](https://jira.ez.no/browse/EZP-28750)
Excerpt from JIRA:
> When trying to access preview for a draft, the "Version information" section contains information about the last published version (instead of the draft that is being previewed). Additionally, the "Back to edit" and "Publish" buttons are disabled.
The issue was introduced in https://github.com/ezsystems/ezpublish-legacy/pull/1296.
It turns out that `$version` variable is used by other templates and it shouldn't be changed, so I renamed it to something more temporary.
=> Fix EZP-28750: Draft preview displays wrong Version information

kernel/classes/ezcontentcachemanager.php, kernel/content/ezcontentoperationcollection.php
> JIRA: https://jira.ez.no/browse/EZP-28404
> Depends on https://github.com/ezsystems/LegacyBridge/pull/140
This PR adjusts legacy to the changes are introduced in https://github.com/ezsystems/LegacyBridge/pull/140 (see for more details).
=> EZP-28736: SPI cache not cleared when a content is published via a delayed publication workflow

kernel/classes/datatypes/ezbinaryfile/ezbinaryfiletype.php
Messes up the error.log on every store/publish action with any contenttype including ezbinaryfile.
Additionally does some unneeded checks for removing the binary file, but that is rather theoretically.
Aligned the new variable name with the one above.
=> Typo in variable name results in PHP Notice and unneeded file deletion checks on ezbinaryfile store/publish.

lib/ezi18n/classes/ezcharsetinfo.php
> https://jira.ez.no/browse/EZP-28950
eZ legacy does not recognize `utf8mb4` charset, instead falling back to conversion to a single byte charset set by `eZTextCodec`, which results in the following beautiful error messages:
```
Query error (1064): You have an error in your SQL syntax; check the manual that
corresponds to your MySQL server version for the right syntax to use near '???????????????????????????????????????????????????????????
?????????????????????' at line 1. Query: ?????????????????????????????????????????????????????????????????
??????????????????????????????????????????????????????????????????????
[ May 23 2018 10:47:03 ] Unexpected error, the message was : Call to a member function
attribute() on null in vendor/ezsystems/legacy-bridge/bundle/LegacyMapper/Security.php on …
```
=> EZP-28950: Add support for utf8mb4 charset to i18n

kernel/classes/datatypes/ezimage/ezimagefile.php
JIRA issue: https://jira.ez.no/browse/EZP-29039
As described in JIRA issue, the image aliases are always set as expired in DFS `ezdfsfile` table during draft rejection under two conditions existing simultaneously:
* Image parent node (folder/gallery) has to has special characters in the name/title (for instance quotes)
* `[URLTranslator]` setting needs to be set as `TransformationGroup=urlalias_iri`
Due to `TransformationGroup=urlalias_iri` setting names of directories on the filesystem also contain special characters.
An image is saved to the `ezcontentobject_attribute`.`data_text` as XML. Each XML node which represents image/image alias has attribute `url`. Under the mentioned conditions, during the conversion phase, the value of this attribute is created from the file path and all …
=> EZP-29039: Image aliases expiry on draft discard

design/admin/stylesheets/pagelayout.css, design/admin/templates/pagelayout.tpl, design/admin/templates/parts/content/menu.tpl, design/admin/templates/parts/media/menu.tpl, design/admin/templates/parts/my/menu.tpl, design/admin/templates/parts/setup/menu.tpl, design/admin/templates/parts/shop/menu.tpl, design/admin/templates/parts/user/menu.tpl, design/admin/templates/parts/visual/menu.tpl
- fixed height on the width controller element causes the user to get
'stuck' and unable to scroll back to the top when clicking on a link
targeting an in page anchor
The bug is also noted in this Jira ticket:
https://jira.ez.no/browse/EZP-29210
=> EZP-29210: Fix admin UI anchor link scroll bug

kernel/classes/datatypes/ezuser/ezuser.php
> Fixes https://jira.ez.no/browse/EZP-29021
> QA
It seems the legacy part of https://jira.ez.no/browse/EZP-28214 broke `eZUser::PASSWORD_HASH_MD5_PASSWORD`. This fixes it.
=> EZP-29021: User can't login using PASSWORD_HASH_MD5_PASSWORD

kernel/classes/datatypes/ezxmltext/handlers/output/ezxhtmlxmloutput.php, settings/ezxml.ini
> Fix https://jira.ez.no/browse/EZP-29033
> QA
The security fix EZSA-2018-001 ensured that the names of protected content could not be leaked by making content/node links to it. The links would normally be rendered as URL aliases, which leaks the content name. After the fix, links are rendered empty, making them non-functional.
This fixes it: When the user doesn't have read access to the linked node/object, show a `/content/view/full/<nodeId>` link rather than nothing. So the link is functional, the user is told they don't have access, while not leaking the content name. This is the new default behaviour. You can set `ezxml.ini [ezxhtml] ShowURLAliasForProtectedLinks=enabled` to get the old, pre-security-fix behaviour (always URL alias).
This affects only eznode/ezobject links in XML …
=> EZP-29033: [Legacy] Don't remove links user has no access to

kernel/classes/datatypes/ezxmltext/ezxmloutputhandler.php, kernel/classes/datatypes/ezxmltext/handlers/output/ezxhtmlxmloutput.php
> Fix https://jira.ez.no/browse/EZP-29085
> Sent to QA
Copied from Slack:
Seems like nodeID is forced to convert to string at https://github.com/ezsystems/ezpublish-legacy/blob/master/kernel/classes/datatypes/ezxmltext/ezxmloutputhandler.php#L278 and https://github.com/ezsystems/ezpublish-legacy/blob/master/kernel/classes/datatypes/ezxmltext/ezxmloutputhandler.php#L285
But http://php.net/manual/en/language.types.array.php says:
_Additionally the following key casts will occur:
Strings containing valid decimal integers, unless the number is preceded by a + sign, will be cast to the integer type. E.g. the key “8” will actually be stored under 8. On the other hand “08" will not be cast, as it isn’t a valid decimal integer._
I.e. the string conversion is pointless, the array index will be an …
=> EZP-29085: Force to use integer keys in eZXMLOutputHandler->NodeArray

kernel/content/ezcontentoperationcollection.php
In the back-end, when you add a new location to an existing content, or remove one, the search index is not updated.
=> Update index when adding/removing node assignment

doc/bc/5.90/relation_indexing.md, kernel/classes/datatypes/ezobjectrelation/ezobjectrelationtype.php, kernel/classes/datatypes/ezobjectrelationlist/ezobjectrelationlisttype.php, kernel/classes/ezcontentobjectattribute.php, kernel/classes/ezdatatype.php, kernel/search/plugins/ezsearchengine/ezsearchengine.php
JIRA issue: [EZP-27101](https://jira.ez.no/browse/EZP-27101)
When retrieving the search metadata from objects containing "Object relation" and "Object relations" field type, there is a recursion protection in place that ensures that there is no infinite recursion caused by circular references. However, it only checks if the certain object was already processed and this is causing problems when the same object is referenced from two different fields (as described in [EZP-27101](https://jira.ez.no/browse/EZP-27101)). 
This PR removes the recursion completely by making the relations load metadata only one level deep. By removing recursion, I was also able to remove the recursion protection, which solves the original issue.
This PR introduces a slight BC break because it changes logic …
=> EZP-27101: Remove recursion when retrieving search metadata for relation fields

update/common/scripts/5.4/cleanuntranslatablerelations.php
MySQL 5.7 is strict by default and will error out on the incorrect GROUP BY in the update script (see diff).
=> EZP-29350: Make query compatible with strict MySQL

extension/ezoe/design/standard/templates/ezoe/customattributes/link.tpl
https://jira.ez.no/browse/EZP-29170
This is pull request replaces https://github.com/ezsystems/ezpublish-legacy/pull/1362
Now custom tags properly supports multiple link attributes on multiple tags.
Fixed issues since last pull request:
- Identified one issue when changing the link source type to eznode the code would throw errors.
- Identified one issue when editing objects with multiple customtags with multiple link types the code would throw errors when editing a custom tag containing multiple links.
- Identified one issue where link source would be pre-populated with content from other link types that had already an existing source.
Original description. 
The first time you select a node in a custom tag "link" attribute, it shows you the name of the node selected. However, if you open …
=> EZP-29170: Custom tag attribute of "link" type should indicate what node is selected #1362

tests/tests/lib/ezsoap/ezsoapclient_test.php, tests/tests/lib/ezutils/ezhttptool_test.php
Whoops, forgot about these old tests when killing critmon.
As discovered in https://github.com/ezsystems/ezpublish-legacy/pull/1373
=> Skip tests that depend on critmon1.ez.no as it has been shut down

lib/ezsession/classes/ezsession.php
| Question           | Answer
| ------------------ | ------------------
| **JIRA issue**     | [EZP-29390](https://jira.ez.no/browse/EZP-29390)
| **Bug**| yes
| **New feature**    | no
| **Target version** | `master` 
PHP 7.2 emits warning `PHP Warning:  session_name(): Cannot change session name when session is active`. In the previous versions, it was not possible to change session name when a session already exists too, but there was no warning.
More info: http://php.net/manual/en/function.session-name.php#refsect1-function.session-name-changelog & https://stackoverflow.com/questions/47700336/php-7-2-warning-cannot-change-session-name-when-session-is-active
=> EZP-29390: [Legacy] PHP Warning: Cannot change session name when session is active

lib/ezsession/classes/ezsession.php
Question | Answer
-- | --
JIRA issue | [EZP-29418](https://jira.ez.no/browse/EZP-29418)
Bug | yes
New feature | no
Target version | 2017.12
Regression from https://github.com/ezsystems/ezpublish-legacy/pull/1373
When a sessionName is set, it will generate a new one in the else if section.
=> Fix EZP-29418: Wrong Session Name after EZP-29390

kernel/classes/ezcontentobjecttreenode.php, kernel/classes/ezsection.php
| Question           | Answer
| ------------------ | ------------------
| **JIRA issue**     | [EZP-29379](https://jira.ez.no/browse/EZP-29379)
| **Bug/Improvement**| yes
| **Target version** | 5.4
Changing section for content inside Details tab updates the database with change but does not commit to solr index. This is because solr indexer is used inside a transaction that updates section id for the object (and when indexing takes place, sections are not changed) and cache for items in subitem tree are never cleared before indexing (so they end up indexed with outdated data).
This PR fixes the above problems.
=> EZP-29379: Fixed changing of section not committing to the solr index

composer.json, kernel/classes/datatypes/ezmultioption/ezmultioption.php, kernel/classes/ezdatatype.php, kernel/classes/ezrssexportitem.php, kernel/classes/ezsslzone.php, kernel/classes/workflowtypes/event/ezapprove/ezapprovetype.php, kernel/private/classes/clusterfilehandlers/ezdfsfilehandler.php, kernel/shop/editvatrule.php, lib/eztemplate/classes/eztemplatecompiler.php, lib/eztemplate/classes/eztemplatenodetool.php, lib/ezutils/classes/ezphpcreator.php
=> [PHP] Fix some PHP 7.2 deprecations

kernel/classes/ezcontentobjecttreenode.php, kernel/classes/ezsection.php, kernel/content/ezcontentoperationcollection.php
This PR is a follow up for https://github.com/ezsystems/ezpublish-legacy/pull/1378
=> Option to skip search engine indexing inside eZContentOperationCollection::updateSection

bin/php/trashpurge.php, kernel/classes/ezcontentobjecttrashnode.php, kernel/private/classes/ezscripttrashpurge.php, kernel/sql/mysql/kernel_schema.sql, kernel/sql/postgresql/kernel_schema.sql
https://jira.ez.no/browse/EZP-28881
**Updated:** eZ Platform equivalent update: https://github.com/ezsystems/ezpublish-kernel/pull/2379
The eZ Publish trash can really fill and make it difficult to find something in the trash. It would be nice to be able to have a script that periodically clears out items that are older than "n days" (for example). In order to do this, we would need a field for objects in the trash that saves the "date object was trashed". It has been often requested by clients.
This pull request changes the eZContentObjectTrashNode so it stores the date the object has been trashed and then we can run the trashpurge script like:
php bin/php/trashpurge.php -s manage  --trashed-days=1
By default trashed days will be 0, so all content will be purged, if set, only objects …
=> EZP-28881: Add a field to support "date object was trashed"

lib/ezi18n/classes/eztranslationcache.php, lib/eztemplate/classes/eztemplatetreecache.php, lib/ezutils/classes/ezextension.php
Some caches doesn't use atomic writes when writing to disk. This can lead to corrupt cache files if multiple processes tries to write to the same file at the same time.
=> Atomic cache writes to prevent corrupt caches.

kernel/classes/ezcollaborationgroup.php, kernel/classes/ezcollaborationitem.php, kernel/classes/ezcontentobjecttreenode.php, kernel/classes/ezsiteaccess.php, kernel/package/ezpackagefunctioncollection.php, kernel/search/plugins/ezsearchengine/ezsearchengine.php, lib/ezutils/classes/ezmoduleoperationinfo.php
```
$ php7.3 -v ; find . -name '*.php' -exec php7.3 -l {} \;| grep -v '^No syntax errors'
```
Results in:
```
PHP Warning:  "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in ./kernel/classes/ezcollaborationitem.php on line 392
PHP Warning:  "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in ./kernel/classes/ezcontentobjecttreenode.php on line 734
PHP Warning:  "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in ./kernel/classes/ezcollaborationgroup.php on line 229
PHP Warning:  "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in ./kernel/classes/ezsiteaccess.php on line 160
PHP Warning:  "continue" targeting switch is equivalent to …
```
=> Fix warnings about continue inside switch on PHP 7.3

kernel/classes/ezcontentobject.php
Since https://github.com/ezsystems/ezpublish-legacy/commit/5651fb9c9ce8dea1105cb12f5598500218150865, the `eZContentObject::removeThis()` method uses the variable `$additionalNodes` without defining it. The consequence is that additional nodes other than the one specificed will not be removed, leading to inconsistency. Possibly to content without a main node.
* requirement
** node id is used as parameter
** used node id is the main one
* context : known context is the unpublish feature
=> eZContentObject::removeThis() does not remove assigned nodes

kernel/setup/steps/ezstep_installer.php
> Fixes https://jira.ez.no/browse/EZP-29573
> Ready for review
When creating a database in `utf8mb4`, the legacy installer complains that only `utf-8` is supported. Since `utf8mb4` is recommended now we should support both.
`utf8mb4` is not available in every database eZ Publish 5.x supports, but then people won't be able to create such a DB, so it won't be a problem.
**NB:** Since we have not backported the utf8mb4 schema changes, in order for this to work one has to first create the database, then apply the changes in the [advisory](http://share.ez.no/community-project/security-advisories/ezsa-2018-003-4-byte-utf-8-in-mysql-mariadb), and then run the installer.
=> EZP-29573: Legacy installer should allow utf8mb4 charset

autoload/ezp_kernel.php, kernel/classes/datatypes/ezdate/ezdatetype.php, lib/ezutils/classes/eztimestamp.php
JIRA issue: [EZP-29279](https://jira.ez.no/browse/EZP-29279)
Replaces #1384
Currently, in Legacy, the timestamp stored in the database is always midnight in the server's timezone, while in Platform it is always in UTC.
This PR modifies `eZDateType` class so timestamps are converted to UTC before being stored and are converted back to Local Timezone timestamp on retrieval.
=> EZP-29279: Values of Date Field Type should be handled in UTC only

kernel/classes/datatypes/ezuser/ezuser.php, kernel/classes/datatypes/ezuser/ezusertype.php, kernel/user/ezuseroperationcollection.php, tests/tests/kernel/datatypes/ezuser/ezusertype_regression.php
The issue and steps to reproduce it are described here:
https://jira.ez.no/browse/EZP-29096
Or use those steps:
* Create a new user account
* Do not fill any values in the form
* Close the browser tab
* Try to create a new user account
* You will get a transaction error
This patch will prevent the user creation to store any draft data into the DB unless the editor specified a user login.
=> EZP-29096: Do not store empty draft values in DB

extension/ezoe/ezxmltext/handlers/input/ezoexmlinput.php
https://jira.ez.no/browse/EZP-30160
Currently eZOE doesn't show up on Android due to an issue several years ago that lead devs to just show the textarea for Android devices, but as in 2019 it should work without problems on Android devices so we can remove the line blocking for Android devices.
=> EZP-30160 eZOE should work on Android

lib/ezsession/classes/ezpsessionhandlerphp.php, lib/ezsession/classes/ezsession.php
In ezp there is a *session wrapper*:
https://github.com/ezsystems/ezpublish-legacy/blob/master/lib/ezsession/classes/ezsession.php
It has functions like `start`, `regenerate`, `remove` etc.
Those function calls get forwarded to a concrete *session handler* - for example:
https://github.com/ezsystems/ezpublish-legacy/blob/master/lib/ezsession/classes/ezpsessionhandlerphp.php
This *session handler* is using the default PHP sessions. But there are also other handlers like a DB handler, storing the session in the DB:
https://github.com/ezsystems/ezpublish-legacy/blob/master/lib/ezsession/classes/ezpsessionhandlerdb.php
The *session wrapper* class is not always forwarding the function calls to the handler class. The function `remove` has concrete code to remove a PHP session. That code should …
=> Forward ezsession::remove to session handlers

kernel/user/ezuseroperationcollection.php
https://jira.ez.no/browse/EZP-30383
If you use the legacy bridge and an Administration Interface (legacy or Netgen Admin UI) that uses /user/password:
If you use "Change password" (which goes to /user/password) and then change the password, when you try to log in through a siteaccess that has "legacy_mode: false" (front-end or Netgen Admin UI) it won't work with the new password. It will work with the old password. You must clear the view cache for that user for the new password to work.
If you use "Change Information", which edits the user object and then change the user's password, this works, because it natively clears the view cache for that user.
In summary: this issue can be reproduced by 1) changing your password with the /user/password module view; 2) logging in to any siteaccess …
=> Fix EZP-30383: Change password with "legacy_mode: false" does not properly clear the cache

design/admin/templates/navigator/google.tpl
legacy template navigator/google.tpl - PHP Notice - Array to string conversion
ignoring new view_parameters value _custom
=> fix EZP-30293 : PHP Notice - Array to string

kernel/content/ezcontentoperationcollection.php
Fix issue with cache not cleared on node visibility change.
Search index takes wrong visibility status from cache.
Todo:
=> FIX cache not cleared on node visibility change

cronjobs/linkcheck.php, design/admin/templates/setup/datatype_code.tpl, design/standard/templates/setup/datatype_code.tpl, extension/ezoe/ezxmltext/handlers/input/ezoexmlinput.php, extension/ezoe/modules/ezoe/classes/GoogleSpell.php, extension/ezoe/modules/ezoe/classes/SpellChecker.php, extension/ezoe/modules/ezoe/classes/utils/mcejson.php, extension/ezoe/modules/ezoe/spellcheck_rpc.php, kernel/classes/datatypes/ezxmltext/ezxmloutputhandler.php, kernel/classes/ezpersistentobject.php, kernel/private/classes/clusterfilehandlers/dfsbackends/mysqli.php, kernel/setup/steps/ezstep_site_types.php, kernel/url/view.php, lib/ezdb/classes/ezmysqlidb.php, lib/ezdbschema/classes/ezmysqlschema.php, lib/ezfile/classes/ezgzipzlibcompressionhandler.php, lib/ezpdf/classes/class.ezpdftable.php, lib/ezpdf/classes/class.pdf.php, lib/ezsoap/classes/ezsoapserver.php, lib/ezutils/classes/ezfiletransport.php, lib/ezutils/classes/ezsendmailtransport.php, tests/toolkit/extras/tests-files/workflowevent_regression_fetchtemplaterepeat.php
Continuation of https://github.com/ezsystems/ezpublish-legacy/pull/1390
=> PHP 5.3, 5.5, 5.6 and 7.0 deprecation fixes

kernel/classes/datatypes/ezuser/ezldapuser.php, kernel/classes/datatypes/ezuser/eztextfileuser.php, kernel/classes/datatypes/ezuser/ezuser.php
> https://jira.ez.no/browse/EZP-29703
> Ready for review
Users created by the LDAP login handler have password_hash_type = 0 and password_hash is empty string. On login the standard login handler runs first. It currently doesn't recognise these users and logs an error: `Password hash type ID '0' is not recognized. Defaulting to eZUser::DEFAULT_PASSWORD_HASH.` We should accept this case without errors.
Resolved by adding new type `eZUser::PASSWORD_HASH_EMPTY = 0` and by not running `createHash()` for this hash type. Log error if it still happens.
=> EZP-29703: Legacy LDAP users cause error message on login

kernel/classes/datatypes/ezuser/ezuser.php, lib/eztemplate/classes/eztemplateforeachfunction.php, lib/eztemplate/classes/eztemplateforfunction.php
This does not imply full MYSQL8 support, but at least it makes it possible to login.
=> [2019.03] Some fixes for MySQL8 and PHP7.3

extension/ezformtoken/event/ezxformtoken.php
Since 5.0 ezxFormToken code has been operating in two modes:
- Default pure legacy mode using `ezxform_token` as form name
- Symfony mode using `_token` as form name _(if symfony settings are in default state)_
However quite some legacy code hard codes the default name, at least for javacript usage.
In 5.x this inconsistency was solved by setting Symfony to use `field_name: ezxform_token`
For Platform + legacy bridge that is no longer the case, and neither do we want to change the field_name by default. So this changes the logic so that ezxFormToken is cable of handling both at the same time.
Closes #1420
@thiagocamposviana Could you have a look and test if this solves your issue?
=> EZP-30161: Handle form token in both custom and also for historical reasons default value

extension/ezoe/design/standard/templates/ezoe/tag_custom.tpl
The sub (subscript) and sup (superscript) tags work, but there is a UI issue.
Hitting "Ok" once adds the tag, but does not close the dialog. The dialog only closes upon clicking "Cancel."
While the dialog is open, each click of "Ok" after the first inserts the highlighted text at the beginning of the paragraph, in the sub or sup style.
Hitting "Cancel" is the only way out, which makes the necessary workflow:
Select text
Select Custom tags
Select "Sup"
Click OK
Click Cancel
**Reproduce / Testing instructions**
Select text
Select Custom tags
Select "Sup"
Click OK => Dialog remains open
Click OL => Duplicate text inserted at beginning of paragraph.
Tested with: Mac Chrome.
=> Popup for the custom tag sub/sup fixed

kernel/layout/set.php, kernel/private/classes/ezpkernelweb.php
https://jira.ez.no/browse/EZP-30718
The Rerun URL instructions get trapped in the view cache (for hidden pages) because the redundant check for the module exit status can never pass once a page is cached.
The check against "rerun_uri" in the module parameters is sufficient.
=> Fix EZP-30718: Allow RerunURL to be used on hidden pages

kernel/private/classes/clusterfilehandlers/ezdfsfilehandler.php
Only check cache generation timeout when generation has actually started, to avoid SQL error.
Calling `DFSHandler::checkCacheGenerationTimeout()` leads to an SQL error if cache generation hasn't started. In that case, the start timestamp is `false` which ends up as an empty string in the mysqli query. Fix this by not checking, when the timestamp is false. Also fixes CS.
Open questions:
- Is the fact that this happens, a symptom for a bigger problem, or is it really just a long-lived bug?
- ~Would it be more correct to fix this within `checkCacheGenerationTimeout()`?~ Done.
=> DFS: Cache gen. timeout check only when needed

kernel/classes/ezurlaliasml.php, settings/site.ini
https://jira.ez.no/browse/EZP-30767
It is not desirable to load the homepage on what should otherwise be a 404 page.
To prevent a BC break, simply allow this behavior to be overridden.
=> Fix EZP-30767: Allow the developer to override the page to load on a partial URL alias path

update/database/mysql/5.0/dbupdate-4.7.0-to-5.0.0.sql, update/database/postgresql/5.0/dbupdate-4.7.0-to-5.0.0.sql
In some edge cases there may be more than one user returned when executing:
`SELECT ezuser.contentobject_id FROM ezuser WHERE ezuser.email = ezgeneral_digest_user_settings.address` which result in migration script failing with error:
`ERROR 1242 (21000): Subquery returns more than 1 row`
This PR fixes this, limiting the query to return a single row.
=> Updated dbupdate scripts so they will no longer fail when there are multiple users with the same e-mail

bin/php/trashpurge.php
On a recent client work we noticed that the trashpurge.php wasn't working as expected.
This PR fix that issue.
Summary:          
The following line within the trashpurge.php script:
`$options['trashed-days']    ? strtotime( "-{$options['trashed-days']} days" ) : null`
Is converting the trashed days into the wrong value. 
This is because we already have the same strtotime function in here:
https://github.com/ezsystems/ezpublish-legacy/blob/2019.03/kernel/private/classes/ezscripttrashpurge.php#L88
The commit fix that issue.
More info within the Jira ticket:
JIRA ticket: https://jira.ez.no/browse/EZP-30834
Thanks!
=> EZP-30834: remove strtotime function from the trashed-days option

kernel/content/search.php
**Background**
Media content search results through embedded browse on admin site looses "media" context upon pagination and returns much larger search result.
**Testing instructions**
* In the media lib, do a search that returns more that one page of result sets (you may need to create some dummy content for that)
* On that result set, click on page 2
* Confirm you are still showing result sets in context of only the media lib
(Without this pull request, you would be in the context of the 'Content Structure' and it would potentially return more result entries)
=> Fixing search in media lib which used to loose context

lib/ezutils/classes/ezuri.php
Fix of issue introduced in 07de12622320c4648dd03d20647ac012a1411d90 `Fix EZP-23086: Image thumbnail not shown on backend if alias contains quotes` when escaping was introduced.
=> Fix transformURI() on ignoreIndexDir & ! htmlEscape

design/admin/templates/content/datatype/view/ezxmltags/literal.tpl
Many sites support literal HTML for front-end sites. However, we have found this to be nothing but damaging for the Administration Interface, whether that's JavaScript breaking the functionality or CSS breaking the layout. The simple fix is to disable support for the "html" literal tag class in the Administration Interface.
=> EZP-29953: Do not support literal HTML in the Administration Interface

extension/ezjscore/classes/ezjscajaxcontent.php, extension/ezoe/design/standard/javascript/ezoe/popup_utils.js, extension/ezoe/design/standard/templates/ezoe/tag_embed_images.tpl, extension/ezoe/ezxmltext/handlers/input/ezoexmlinput.php
After using AWS S3 as the source of external images, they do not appear in the rich text editor and in the modal of inserting images, this pull request will be resolved this problem.
=> Show images after used url_prefix

kernel/classes/datatypes/ezobjectrelationlist/ezobjectrelationlisttype.php
The call to get a post variable `$http->postVariable( $postVariableName )` sometimes returned `null`.
Resulting in `count(null)`, which triggers a warning.
Ref. phpdoc changelog for count: 
[https://www.php.net/manual/en/function.count.php#refsect1-function.count-changelog](https://www.php.net/manual/en/function.count.php#refsect1-function.count-changelog)
=> PHP7.2 fix: Added array check before count.

.travis.yml
The 5.5 builds fail as the archive no longer exists. This PR switches to 5.6 rather than dropping the build entirely, in order to keep a postgres build on 5.x.
`5.5 is not pre-installed; installing`
`Downloading archive: https://storage.googleapis.com/travis-ci-language-archives/php/binaries/ubuntu/16.04/x86_64/php-5.5.tar.bz2`
`$ curl -sSf --retry 5 -o archive.tar.bz2 $archive_url && tar xjf archive.tar.bz2 --directory /`
`curl: (22) The requested URL returned error: 404 Not Found`
=> Travis: Drop missing 5.5 build

settings/contentstructuremenu.ini
Update the set definition to an empty array.
Instead of false, if not set, it uses the sorting defined for each node (from the Ordering tab).
=> EZP-30416: INI settings don't support loose typing

lib/ezutils/classes/eztimestamp.php
JIRA issue: [EZP-32018](https://jira.ez.no/browse/EZP-32018)
Empty field value for `ezdate` fieldtype has been handled additionally.
=> EZP-32018: Fixed empty ezdate field transformation
