ezsystems/ezpublish-legacy

cronjobs/indexcontent.php
Link: https://jira.ez.no/browse/EZP-23835
=> Fix EZP-23835: pgsql requires columns in groupby

kernel/private/classes/ezpcontentpublishingqueueprocessor.php
JIRA: https://jira.ez.no/browse/EZP-23870
With async publishing script, expiry.php data is being loaded at the start and saved at every publish (through script-shutdown of the forked child process.
Because async publishing is a long-running script/daemon, some expiry keys are not modified and end up overwriting possibly newer timestamps (for example from a cache-clear command).
This resolves it by re-loading expiry timestamps before the publish operation.
=> Fix EZP-23870: async publishing caused stale expiry timestamps.

kernel/private/classes/ezpkernel.php
=> Fix PHP version warning: 5.3.3, not just 5.3.

index_rest.php
> https://jira.ez.no/browse/EZP-24113
Ensures AlwaysLog is honored.
Note that eZDebug error handling needs to be changed in order for logs to be written.
=> Fix EZP-24113: eZ REST API v1: all eZ log files except error.log are disabled unless DebugOutput=enabled

kernel/private/classes/clusterfilehandlers/dfsbackends/mysqli.php
Complete PHPDocs enhance the joy of coding :).
Cheers
:octocat: Jérôme
=> eZDFSFileHandlerMySQLiBackend: Added/fixed PHPDocs and shortened inline comments

kernel/classes/datatypes/ezxmltext/ezxmltexttype.php
JIRA: https://jira.ez.no/browse/EZP-24521
In eZContentObject::purge(),  for every attribute attribute (for every version) the deleteStoredObjectAttribute() function is called.
For contents with multiple versions, removing the urls linked to ezxml contents can have an impact on performance.
This optimizes `eZXMLTextType::deleteStoredObjectAttribute()` by executing this operation only once per attribute when no version is given (removing data for all versions).
=> Fix EZP-24521: Performance in ezxmltexttype attribute deletion

share/translations/fre-FR/translation.ts
https://jira.ez.no/browse/EZP-24631
=> Fix EZP-24631: Typo in the french registration confirmation email

design/admin/templates/user/login.tpl
Link: https://jira.ez.no/browse/EZP-24733
It is confusing to show the Register link if user/register is disabled.
=> Fix EZP-24733: Do not show Register link if user/register is disabled

kernel/setup/steps/ezstep_welcome.php
https://jira.ez.no/browse/EZP-24702
Needed for @vidarl's work on ezpublish-docker project to simplify it down to just use the code as is and not workaround issues.
=> EZP-24702: Allow Setup Wizard to work non interactively with kickstart data

lib/ezutils/classes/ezhttptool.php, settings/site.ini
This implements JIRA https://jira.ez.no/browse/EZP-20547, also resolves https://jira.ez.no/browse/EZP-24738
=> EZP-20547: Allow specifying max. connect timeout for link check

update/common/scripts/5.4/cleanupfieldvaluerelations.php
This PR resolves issue https://jira.ez.no/browse/EZP-22408
This implements cleanup script.
For more details see `ezpublish-kernel` PR for the same issue at https://github.com/ezsystems/ezpublish-kernel/pull/993.
=> Fix EZP-22408: Deleting a content does not remove references to this content in relation(list) fields

autoload.php, bin/php/ezpgenerateautoloads.php, config.php-RECOMMENDED
> http://jira.ez.no/browse/EZP-25110
Renames the `ezpublish` folder to `app`.
Depends on https://github.com/ezsystems/ezplatform/pull/70
=> EZP-25110: Rename ezpublish folder name to app

update/common/scripts/5.4/cleanuntranslatablerelations.php
JIRA: https://jira.ez.no/browse/EZP-25292
=> Fix EZP-25292: fix stale relations for non-translatable attributes.

kernel/classes/datatypes/ezobjectrelationlist/ezobjectrelationlisttype.php
JIRA: https://jira.ez.no/browse/EZP-25065
Follow up on #1217
=> Fix EZP-25065: non-translatable object relation list not updated.

kernel/classes/ezscript.php
> https://jira.ez.no/browse/EZP-25856
Makes use of PHP 7 less noisy :wink:
=> Fix EZP-25856: Silent deprecation errors in ezpublish-legacy

lib/ezutils/classes/ezextension.php
Replaces: https://github.com/ezsystems/ezpublish-legacy/pull/1246
=> EZP-25771: Verify existence of constructor in eZExtension->getHandler()

update/common/scripts/updatenbxmlcontents.php
JIRA: https://jira.ez.no/browse/EZP-26058
=> EZP-26058: update script for non-breaking spaces in ezxmltext

update/common/scripts/updatenbxmlcontents.php
Jira: https://jira.ez.no/browse/EZP-26224
=> Fix EZP-26224: escape xml data string in update script

kernel/content/ezcontentoperationcollection.php
> Issue: https://jira.ez.no/browse/EZP-27011
Edited & Tested by @vnivuahc, ref: https://github.com/netgen/ezplatformsearch/issues/11
Ready for review @emodric @yannickroger @glye
=> EZP-27011: Solr index not updated when changing a content priority

cronjobs/indexcontent.php
https://jira.ez.no/browse/EZP-24919
=> Fix EZP-24919: Clear view/content cache when an object gets re-indexed

kernel/classes/datatypes/ezuser/ezuser.php
> https://jira.ez.no/browse/EZP-27737
The fixes a regression after https://github.com/ezsystems/ezpublish-legacy/commit/134b652e66a399743ba158bf06c101c8abca7bd4
=> EZP-27737: Load correct groups/roles in ezuser

kernel/private/classes/ezpkerneltreemenu.php
JIRA: https://jira.ez.no/browse/EZP-27803
=> Fix EZP-27803: Wrong URLs in Treemenu if Platform is installed in a sub-directory

kernel/content/attribute_edit.php
Correct logic of c95ee808ea836a2f3d3b83876bafbfb208dde4a0
=> EZP-27975: Support post_max_size value set to 0 during content/publish in UI

composer.json
Wondering why this was not done before :)
=> Bump master to 2017.10

design/standard/templates/content/datatype/edit/ezobjectrelation.tpl
=> EZP-28120: Typo in ezobjectrelation.tpl as of 2017.08

kernel/content/module.php
https://jira.ez.no/browse/EZP-28470
=> EZP-28470: Allow state limitation on manage_locations

kernel/classes/datatypes/ezuser/ezuser.php
> Fix https://jira.ez.no/browse/EZP-28214 for legacy
> For new stack, see https://github.com/ezsystems/ezpublish-kernel/pull/2171
> Sent to QA
Invalid password hash type should not be ignored: Log an error if an invalid password hash type is specified. Fall back to the default hash type (currently bcrypt).
=> EZP-28214: Password hash silently defaults to MD5

update/common/scripts/5.4/fixtrashedimagereferences.php
`continue` used outside of loop.
=> Fixed fatal error

kernel/content/edit.php
ErrorException (E_WARNING)
Illegal string offset 'path'
=> Fixed php7 warning

kernel/classes/datatypes/ezobjectrelationlist/ezobjectrelationlisttype.php
Fixes a fatal error of the issue #29400 : https://jira.ez.no/browse/EZP-29400
=> EZP-29400 : ezobjectrelationlist - fix fatal error

lib/ezi18n/classes/eztstranslator.php
Ticket: https://jira.ez.no/browse/EZP-29598
=> EZP-29598: Prevent race condition when generating TS cache

kernel/classes/ezcontentuploadhandler.php
To avoid issues for ezodf, add bc constructor.
See: https://github.com/ezsystems/ezodf/pull/18
Todo:
=> Add BC constructor for eZContentUploadHandler

share/db_schema.dba, update/database/mysql/7.3/dbupdate-5.4.0-to-6.12.0.sql, update/database/postgresql/7.3/dbupdate-5.4.0-to-6.12.0.sql
~Let's see what Travis says, locally I have some errors still with this. But at least it runs true all so it might be unrelated.~
EDIT: First one passing, so calling for review and will merge if all passes.
=> Add missing SQL updates & schema change for trashed column

kernel/classes/datatypes/ezimage/ezimagetype.php, kernel/content/attribute_edit.php
This pull request solves <https://jira.ez.no/browse/EZP-29723> while still fixing <https://jira.ez.no/browse/EZP-23088>.
Ported to 2017.12 as asked for in #1412.
=> EZP-29723: Content object attributes not set properly

kernel/classes/ezcontentobject.php, kernel/classes/ezcontentobjectversion.php, kernel/content/ezcontentoperationcollection.php, kernel/content/removeeditversion.php, kernel/private/classes/clusterfilehandlers/dfsbackends/mysqli.php
This collects all PRs for https://jira.ez.no/browse/EZP-28681 except https://github.com/ezsystems/ezautosave/pull/27 which is in a different repository.
For testing purposes.
=> EZP-28681: legacy transaction handling 1-5

kernel/classes/ezcontentobjecttreenode.php, tests/tests/kernel/classes/ezcontentobjecttreenode_test2.php
Hi there,
This is a continuation of the work done in here: https://github.com/ezsystems/ezpublish-legacy/pull/1439
I created a new PR because @andrerom asked me to rebase 2019.03 branch but I was having issues. The rebase was complaining about the composer.json. The conflict was easy to fix but some some reason when I was `git rebase --continue` git was stuck unable to finish the rebase so I created this new branch of 2019.03.
I've also added a new commit with the unit test as requested.
Jira ticket: https://jira.ez.no/browse/EZP-30782
Thanks!
=> EZP-30782: allow sorting by trashed field

doc/bc/5.90/php7.md
- fixes spelling
- more clear explanations
=> improve php 7 bc doc

kernel/classes/datatypes/ezobjectrelationlist/ezobjectrelationlisttype.php
https://github.com/ezsystems/ezpublish-legacy/pull/819
=> store can not be called here, because it clears object's data_map

lib/ezutils/classes/eztimestamp.php
JIRA issue: [EZP-32018](https://jira.ez.no/browse/EZP-32018)
Follow up on the following PR: https://github.com/ezsystems/ezpublish-legacy/pull/1464
=> EZP-32018: Added additional validation to ezdate fieldtype
